// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scraping.Web.Entities;

namespace Scraping.Web.Entities.Migrations
{
    [DbContext(typeof(ScrapingWebContext))]
    [Migration("20180827055815_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Scraping.Web.Entities.FOREX.EconomicCalender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Actual");

                    b.Property<string>("Consensus");

                    b.Property<string>("Country");

                    b.Property<string>("Description");

                    b.Property<string>("Event");

                    b.Property<string>("Previous");

                    b.Property<string>("Time")
                        .HasMaxLength(50);

                    b.Property<string>("TimeZone");

                    b.Property<string>("Vol");

                    b.HasKey("Id");

                    b.ToTable("EconomicCalenders");
                });
#pragma warning restore 612, 618
        }
    }
}
